SHARE:
  PUBLIC:
    GATEWAY_CONFIG:
      METHOD: http
      HOST: localhost:8080
  SECURE:
    CORS:
      ORIGIN:
        - 'http://localhost:3000'
        - 'http://localhost:8080'
      METHODS:
        - 'GET'
        - 'PUT'
        - 'POST'
        - 'DELETE'
        - 'PATCH'
        - 'HEAD'
        - 'OPTIONS'
      ALLOWED_HEADERS:
        - '*'
      EXPOSED_HEADERS:
        - '*'
      CREDENTIALS: true
      PREFLIGHT_CONTINUE: false
    JWT:
      JWT_SECRET: jwt_secret
      TOKEN_EXPIRE: 86400
    RABBIT_MQ:
      USERNAME: demo
      PASSWORD: demo
      PROTOCOL: amqps
      HOST: rabbitmq.com
      PORT: 5671
      PRE_FETCH_COUNT: 100
NAME: dev
APP:
  NAME: store
  PORT: 8080
  IP: 0.0.0.0
DATABASE:
  MONGODB:
    USERNAME: 'dungma'
    PASSWORD: 'Demo12345'
    HOST: 'db-2021'
    PORT: 27017
    NAME: store
EMAIl:
  USER: apikey
  PASSWORD: SG.ds4L91tDwTAmuiBRIXxw2jg.wTjG5UZea_kh7-tmy8DC_kCnC-SCZQUdiRt3ptomQgk
  HOST: smtp.sendgrid.net
  PORT: 465
  FROM: dungma@gmail.com
  SECURE: true
